version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supernova
      POSTGRES_DB: notetaking-app

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      PGUSER: postgres
      PGHOST: postgres
      PGDATABASE: notetaking-app
      PGPASSWORD: supernova
      PGPORT: 5432
    depends_on:
      - postgres
